#!/bin/sh
# Desc: Wrapper for iibot based on script by c00kiemon5ter
#
# 2017/Apr/08 @ Zdenek Styblik <stybla@turnovfree.net>
set -e
set -u

check_parser_error()
{
    # shellcheck disable=SC3043
    local value="${1}"
    # shellcheck disable=SC3043
    local label="${2}"
    if [ "${value}" = "parser-error" ]; then
        printf -- "Config parser failed to get value for variable '%s'.\n" "${label}" 1>&2
        exit 1
    fi
}

monitor()
{
    # shellcheck disable=SC3043
    local iipid="${1}"
    tail -f -n1 --pid="${iipid}" "${ircdir}/${network}/${channel}/out" | \
        # NOTE(zstyblik): unfortunately this fetches the last message in channel
        # on startup, therefore ultimately leads to some "repetition".
        # NOTE(zstyblik): format of output changed in v1.8
        while read -r nixtime nick msg; do
            # if msg is by the system ignore it
            if [ "$nick" = '-!-' ]; then
                if printf -- "%s" "${msg}" | grep -q -e ' has joined ' ; then
                    exec "${scripts_dir}/iifriends.py" \
                        --message "${msg}" \
                        --ircd "${ircdir}" \
                        --network "${network}" \
                        --self "${nickname}" > /dev/null &
                fi
                continue
            fi
            # shellcheck disable=SC2034
            nixtime_is_unused="${nixtime}"
            # strip < and >. if msg is by ourself ignore it
            nick=$(printf -- "%s" "${nick}" | sed -e 's@^<@@' | sed -e 's@>$@@')
            if [ "${nick}" = "${nickname}" ]; then
                continue
            fi
            # NOTE(zstyblik): if we have two bots in the same channel, iicmd
            # must be disabled. Why? How about endless loop of URL titles?
            # That's why.
            if [ "${iicmd_enabled}" = "false" ]; then
                continue
            fi

            # if msg contains a url, transform to url command
            if printf -- "%s" "${msg}" | grep -q -E -e 'https?://'; then
                export IICMD_BITLY_GROUP_ID="${bitly_group_id}"
                export IICMD_BITLY_API_TOKEN="${bitly_api_token}"
                exec "${scripts_dir}/iicmd.py" \
                    --nick "${nick}" \
                    --message "url ${msg#\!}" \
                    --ircd "${ircdir}" \
                    --network "${network}" \
                    --channel "${channel}" \
                    --self "${nickname}" | fold -w 255 &
                continue
            fi
            # NOTE: commands MUST start with _!_ and that's why nothing might be
            # happening.
            #
            # if msg is a command, invoke iicmd
            if printf -- "%s" "${msg}" | grep -q -E -e '^!'; then
                exec "${scripts_dir}/iicmd.py" \
                    --nick "${nick}" \
                    --message "${msg#\!}" \
                    --ircd "${ircdir}" \
                    --network "${network}" \
                    --channel "${channel}" \
                    --self "${nickname}" | fold -w 255 &
                continue
            fi
        done > "${ircdir}/${network}/${channel}/in"
}

monitor_link()
{
    # shellcheck disable=SC3043
    local iipid="${1}"
    IFS='
'
    tail -f -n1 --pid="${iipid}" "${ircdir}/${network}/out" | \
        while read -r response; do
            if printf -- "%s" "${response}" | grep -q -i -e 'Closing Link' -E -e "${nickname}.*ping timeout"; then
                printf "Killing bot.\n" 1>&2
                kill "${iipid}"
                break
            fi
        done
}

remove_lock()
{
    if [ -n "${pids}" ]; then
        printf -- "%s" "${pids}" | xargs kill || true
    fi
    rmdir "${LOCK_DIR}"
}

# FIXME: cleanup once systemd unit is updated
IRC_CONFIG=${1:?Supply name of IRC config to use.}
IRC_CONFIG_NAME=$(basename -- "${IRC_CONFIG}")
LOCK_DIR="/tmp/${IRC_CONFIG_NAME}.lock"

scripts_dir=$(dirname -- "${0}")
irc_config_dir=$(dirname -- "${IRC_CONFIG}")
irc_config_toml=$(basename -s .cfg -- "${IRC_CONFIG}")
irc_config_toml=$(basename -s .toml -- "${irc_config_toml}")
irc_config_toml="${irc_config_dir}/${irc_config_toml}.toml"
if [ ! -r "${irc_config_toml}" ]; then
    printf "Config file '%s' doesn't exist or is not readable.\n" \
        "${irc_config_toml}" 1>&2
    exit 2
fi

nickname=$("${scripts_dir}/config_lookup.py" -f "${irc_config_toml}" -s ii.settings -o nickname)
check_parser_error "${nickname}" "nickname"
nickname=${nickname:-"testme"}

network=$("${scripts_dir}/config_lookup.py" -f "${irc_config_toml}" -s ii.settings -o server)
check_parser_error "${network}" "network"
if [ -z "${network}" ]; then
    printf "Name of IRC network must not be empty.\n" 1>&2
    exit 2
fi
ircdir=$("${scripts_dir}/config_lookup.py" -f "${irc_config_toml}" -s ii.settings -o ircdir)
check_parser_error "${ircdir}" "ircdir"
ircdir=${ircdir:-"${HOME}/irc"}

channels=$("${scripts_dir}/config_lookup.py" -f "${irc_config_toml}" -s 'channel.*' -o 'name')
check_parser_error "${channels}" "channels"

iicmd_enabled=$("${scripts_dir}/config_lookup.py" -f "${irc_config_toml}" -s ii.cmd -o enabled)
check_parser_error "${iicmd_enabled}" "iicmd_enabled"
if printf -- "%s" "${iicmd_enabled}" | grep -q -i -e 'true'; then
    iicmd_enabled="true"
else
    iicmd_enabled="false"
fi

bitly_api_token=$("${scripts_dir}/config_lookup.py" -f "${irc_config_toml}" -s bitly -o api_token)
check_parser_error "${bitly_api_token}" "bitly_api_token"
bitly_group_id=$("${scripts_dir}/config_lookup.py" -f "${irc_config_toml}" -s bitly -o group_id)
check_parser_error "${bitly_group_id}" "bitly_group_id"

mkdir -p "${LOCK_DIR}" || \
    ( printf "Failed to create lock for '%s'.\n" "${IRC_CONFIG}" 1>&2; exit 1; )
trap remove_lock INT QUIT TERM EXIT

# some privacy please, thanks
chmod 700 "${ircdir}"
chmod 600 "${ircdir}"/*/ident 1> /dev/null 2>&1 || true

pids=""
# cleanup stale "in" pipes turned into files
find "${ircdir}/${network}/" -name 'in' -type f -delete
# NOTE(zstyblik): if server requires password on connect, then password must be
# stored in ENV variable and the name of ENV variable MUST BE given as CLI arg,
# eg. -k IIPASS.
#
# NOTE(zstyblik): there is no way to know if wrapper or ii failed. There will be
# a PID and RC=0 regardless of failure, therefore these two are worthless.
"${scripts_dir}/ii_wrapper.py" \
    -f "${irc_config_toml}" >> "${ircdir}/${network}.log" 2>&1 &
pid="$!"

# wait for the connection
time_slept=0
while ! test -p "${ircdir}/${network}/in"; do
    sleep 1
    time_slept=$((time_slept + 1))
    if [ ${time_slept} -ge 60 ]; then
        # We either didn't get the connection or something went wrong -> crash.
        #
        # NOTE(zstyblik): we cannot continue without pipe. If we do, then it
        # looks like we will end up with files instead of pipes(which is bad).
        # This doesn't mean that pipe cannot go away later, but still.
        printf "Pipe '%s' still does not exist - giving up.\n" \
            "${ircdir}/${network}/in" 1>&2
        exit 1
    fi
done

monitor_link "$pid" &
pids=$(printf -- "%s %s" "${pids}" $!)

# auth to services
if [ -e "${ircdir}/${network}/ident" ]; then
    printf -- "/j nickserv identify %s\n" \
        "$(cat "${ircdir}/${network}/ident")" > "${ircdir}/${network}/in"
fi
# clean that up - ident passwd is in there
rm -f "${ircdir}/${network}/nickserv/out"

sleep 3
# join channels
for channel in $(printf -- "%s" "${channels}" | tr ',' ' '); do
    # NOTE(zstyblik): if this is first ever join, directory doesn't exist and
    # touch will fail. Fail is ok, just not in this case.
    mkdir -p "${ircdir}/${network}/${channel}"
    rm -f "${ircdir}/${network}/${channel}/in"
    if [ ! -e "${ircdir}/${network}/${channel}/out" ]; then
        touch "${ircdir}/${network}/${channel}/out"
    fi
    printf -- "/j %s\n" "${channel}" > "${ircdir}/${network}/in"
    monitor "${pid}" &
    pids=$(printf -- "%s %s" "${pids}" $!)
done

# if connection is lost, die
wait "${pid}"
remove_lock
trap - INT QUIT TERM EXIT
# EOF
