name: ii-wrapper workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v5
    - name: Install linters
      uses: awalsh128/cache-apt-pkgs-action@v1.5.3
      with:
        packages: devscripts shellcheck
    - name: Run checkbashisms
      run: |
        ./ci/run-checkbashisms.sh
    - name: Run shellcheck
      run: |
        ./ci/run-shellcheck.sh
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
    - name: Reorder Python imports
      run: |
        ./ci/run-reorder-python-imports.sh
    - name: Lint with flake8
      run: |
        ./ci/run-flake8.sh
    - name: Lint with black
      run: |
        ./ci/run-black.sh check || ( ./ci/run-black.sh diff; exit 1 )
    - name: Test with pytest
      run: |
        python -m pytest .
